SELECT EMP_ID, EMP_NAME, SALARY, DEPT_CODE FROM EMPLOYEE; 

SELECT * FROM EMPLOYEE ;

SELECT EMP_ID, EMP_NAME, SALARY, JOB_NAME 
FROM EMPLOYEE 
JOIN JOB USING(JOB_CODE) 
WHERE SALARY > 7000000
ORDER BY SALARY DESC;


SELECT EMP_ID , EMP_NAME , SALARY 
FROM EMPLOYEE 
WHERE SALARY BETWEEN 2000000 AND 7000000
ORDER BY SALARY DESC;


SELECT DEPT_TITLE 
FROM DEPARTMENT ;

SELECT EMP_ID , EMP_NAME , DEPT_TITLE , JOB_NAME 
FROM EMPLOYEE 
LEFT JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID)
JOIN JOB USING (JOB_CODE)
WHERE DEPT_TITLE = '총무부'
ORDER BY JOB_CODE;

SELECT COUNT(*)
FROM DEPARTMENT 
WHERE DEPT_TITLE = 'input';
