-- 1. 

SELECT STUDENT_NAME "학생 이름", STUDENT_ADDRESS "주소지"
FROM TB_STUDENT 
ORDER BY STUDENT_NAME ;

-- 2. 
SELECT STUDENT_NAME , STUDENT_SSN 
FROM TB_STUDENT 
WHERE ABSENCE_YN = 'Y'
ORDER BY STUDENT_SSN DESC;

-- 3. 
SELECT STUDENT_NAME "학생 이름", STUDENT_NO "학번", STUDENT_ADDRESS "거주지 주소"
FROM TB_STUDENT 
WHERE (STUDENT_ADDRESS LIKE '경기도%' OR STUDENT_ADDRESS LIKE '강원도%')
AND STUDENT_NO LIKE '9%'
ORDER BY STUDENT_NAME ;

-- 4. 
SELECT PROFESSOR_NAME , PROFESSOR_SSN 
FROM TB_PROFESSOR 
WHERE DEPARTMENT_NO = '005'
ORDER BY PROFESSOR_SSN ;

-- 5.
SELECT STUDENT_NO , TO_CHAR(POINT , '9.99')
FROM TB_GRADE 
WHERE CLASS_NO = 'C3118100' AND TERM_NO = '200402'
ORDER BY POINT DESC, STUDENT_NO ASC;

-- 6. ????????????? 정렬 순서??? 
SELECT STUDENT_NO , STUDENT_NAME , DEPARTMENT_NAME 
FROM TB_STUDENT 
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
ORDER BY STUDENT_NAME;

-- 7. 
SELECT CLASS_NAME , DEPARTMENT_NAME 
FROM TB_CLASS 
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO);

-- 8. 
SELECT CLASS_NAME , PROFESSOR_NAME
FROM TB_CLASS 
JOIN TB_CLASS_PROFESSOR USING (CLASS_NO)
JOIN TB_PROFESSOR USING (PROFESSOR_NO);

-- 9.
SELECT CLASS_NAME , PROFESSOR_NAME
FROM TB_CLASS CLASS
JOIN TB_CLASS_PROFESSOR USING (CLASS_NO)
JOIN TB_PROFESSOR USING (PROFESSOR_NO)
JOIN TB_DEPARTMENT DEPT ON (CLASS.DEPARTMENT_NO = DEPT.DEPARTMENT_NO)
WHERE CATEGORY = '인문사회' ;

-- 10. 
SELECT STUDENT_NO "학번", STUDENT_NAME "학생 이름", ROUND(AVG(POINT),1) "전체 평점"
FROM TB_STUDENT 
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
JOIN TB_GRADE USING (STUDENT_NO)
WHERE DEPARTMENT_NAME = '음악학과'
GROUP BY STUDENT_NO,STUDENT_NAME
ORDER BY STUDENT_NO; -- 실행 화면 맞춤용 정렬 (문제와 상관 x)

-- 11. 
SELECT DEPARTMENT_NAME , STUDENT_NAME , PROFESSOR_NAME 
FROM TB_STUDENT 
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
JOIN TB_PROFESSOR ON (COACH_PROFESSOR_NO = PROFESSOR_NO)
WHERE STUDENT_NO = 'A313047';

-- 12.
SELECT STUDENT_NAME, TERM_NO "TERM_NAME"
FROM TB_GRADE 
JOIN TB_STUDENT USING (STUDENT_NO)
JOIN TB_CLASS USING (CLASS_NO)
WHERE CLASS_NAME = '인간관계론' AND TERM_NO LIKE '2007%';

-- 13. 
SELECT CLASS_NAME , DEPARTMENT_NAME
FROM TB_CLASS 
LEFT JOIN TB_CLASS_PROFESSOR USING (CLASS_NO)
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE CATEGORY = '예체능' AND PROFESSOR_NO IS NULL; 

-- 14. 
SELECT ENTRANCE_DATE,STUDENT_NAME "학생이름", NVL(PROFESSOR_NAME, '지도교수 미지정') "지도교수"
FROM TB_STUDENT 
LEFT JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
LEFT JOIN TB_PROFESSOR ON (COACH_PROFESSOR_NO = PROFESSOR_NO)
WHERE DEPARTMENT_NAME = '서반아어학과'
ORDER BY ENTRANCE_DATE;

-- 15. **** 진행중
SELECT STUDENT_NO 학번, STUDENT_NAME 이름, DEPARTMENT_NAME "학과 이름", ROUND(AVG(POINT), 8) 평점 
FROM TB_STUDENT 
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO) 
JOIN TB_GRADE USING(STUDENT_NO)
WHERE ABSENCE_YN = 'N' 
GROUP BY STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME 
HAVING AVG(POINT) >= 4.0 
ORDER BY STUDENT_NO;

-- 16. 
-- CLASS_NAME 못넣음
SELECT CLASS_NO, AVG(POINT)
FROM TB_GRADE 
WHERE CLASS_NO IN (SELECT CLASS_NO 
FROM TB_CLASS 
WHERE DEPARTMENT_NO = '034' AND CLASS_TYPE LIKE '전공%')
GROUP BY CLASS_NO;

SELECT CLASS_NO, CLASS_NAME, TRUNC(AVG(POINT),8)
FROM TB_CLASS
JOIN TB_GRADE USING (CLASS_NO)
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '환경조경학과'
AND CLASS_TYPE LIKE '전공%'
GROUP BY CLASS_NO, CLASS_NAME;

-- 16. 환경조경학과 전공과목들의 과목 별 평점을 파악할 수 있는 SQL 문을 작성하시오.
SELECT CLASS_NO , CLASS_NAME , TRUNC(AVG(POINT),8) 
FROM TB_GRADE 
JOIN TB_CLASS USING(CLASS_NO)
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '환경조경학과'
AND SUBSTR(CLASS_TYPE,1,2) = '전공'
GROUP BY CLASS_NO , CLASS_NAME
ORDER BY 1 
;

-- 17.
SELECT STUDENT_NAME , STUDENT_ADDRESS 
FROM TB_STUDENT 
WHERE DEPARTMENT_NO = (SELECT DEPARTMENT_NO 
						FROM TB_STUDENT 
						WHERE STUDENT_NAME ='최경희');
						
					
-- 18.
--SELECT STUDENT_NO , STUDENT_NAME 
SELECT STUDENT_NO, STUDENT_NAME 
FROM (SELECT STUDENT_NO, STUDENT_NAME , AVG(POINT)
	FROM TB_GRADE G2
	JOIN TB_STUDENT USING (STUDENT_NO)
	JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
	WHERE DEPARTMENT_NAME = '국어국문학과'
	GROUP BY STUDENT_NO, STUDENT_NAME 
	ORDER BY AVG(POINT) DESC)
WHERE ROWNUM = 1;

					
					
-- 19. 
-- 최종_FINAL
SELECT DEPARTMENT_NAME , DEPARTMENT_NO, AVG(POINT)
FROM TB_GRADE
JOIN TB_CLASS USING (CLASS_NO)
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE DEPARTMENT_NO IN (SELECT DEPARTMENT_NO 
						FROM TB_DEPARTMENT D1
						WHERE D1.CATEGORY = (SELECT CATEGORY 
											FROM TB_DEPARTMENT D2
											WHERE DEPARTMENT_NAME = '환경조경학과'))
GROUP BY DEPARTMENT_NO, DEPARTMENT_NAME;


SELECT DEPARTMENT_NAME "계열 학과명", ROUND(AVG(POINT),1) 전공평점
FROM TB_DEPARTMENT 
JOIN TB_CLASS USING(DEPARTMENT_NO)
JOIN TB_GRADE USING(CLASS_NO)
WHERE CATEGORY = (SELECT CATEGORY
               FROM TB_DEPARTMENT 
               WHERE DEPARTMENT_NAME = '환경조경학과')
AND CLASS_TYPE = '전공선택'
GROUP BY(DEPARTMENT_NAME)
ORDER BY 1;