SELECT * FROM DEPARTMENT ;

UPDATE DEPARTMENT 
SET DEPT_TITLE = '인사관리부', LOCATION_ID = 'L1'
WHERE DEPT_ID = 'D1' ;

UPDATE DEPARTMENT 
SET DEPT_TITLE = '회계관리부', LOCATION_ID = 'L1'
WHERE DEPT_ID = 'D2' ;

UPDATE DEPARTMENT 
SET DEPT_TITLE = '마케팅부', LOCATION_ID = 'L1'
WHERE DEPT_ID = 'D3' ;

UPDATE DEPARTMENT 
SET DEPT_TITLE = '국내영업부', LOCATION_ID = 'L1'
WHERE DEPT_ID = 'D4' ;

UPDATE DEPARTMENT 
SET DEPT_TITLE = '해외영업1부', LOCATION_ID = 'L2'
WHERE DEPT_ID = 'D5' ;

UPDATE DEPARTMENT 
SET DEPT_TITLE = '해외영업2부', LOCATION_ID = 'L3'
WHERE DEPT_ID = 'D6' ;

UPDATE DEPARTMENT 
SET DEPT_TITLE = '해외영업3부', LOCATION_ID = 'L4'
WHERE DEPT_ID = 'D7' ;

UPDATE DEPARTMENT 
SET DEPT_TITLE = '기술지원부', LOCATION_ID = 'L5'
WHERE DEPT_ID = 'D8' ;

UPDATE DEPARTMENT 
SET DEPT_TITLE = '총무부', LOCATION_ID = 'L1'
WHERE DEPT_ID = 'D9' ;
