-- 1.
-- 춘 기술대학교의 학과 이름과 계열을 표시하시오
-- 단, 출력 헤더는 "학과 명", "계열" 으로 표시하도록 한다. 
SELECT DEPARTMENT_NAME "학과 명" , CATEGORY "계열" 
FROM TB_DEPARTMENT;

-- 2.

SELECT DEPARTMENT_NAME||'의 정원은 '||CAPACITY||' 명 입니다.' AS "학과별 정원"
FROM TB_DEPARTMENT ;

-- 3. 
SELECT STUDENT_NAME 
FROM TB_STUDENT
WHERE DEPARTMENT_NO = 001 AND ABSENCE_YN = 'Y' AND SUBSTR(STUDENT_SSN , 8, 1)='2';

-- 4. 
SELECT STUDENT_NAME 
FROM TB_STUDENT 
WHERE STUDENT_NO IN ('A513079','A513090','A513091','A513110','A513119')
ORDER BY STUDENT_NAME DESC ;

-- 5. 
SELECT DEPARTMENT_NAME , CATEGORY
FROM TB_DEPARTMENT 
WHERE CAPACITY >= 20 AND CAPACITY <= 30;

-- 6. 
SELECT PROFESSOR_NAME 
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO IS NULL;

-- 7. 
SELECT * 
FROM TB_STUDENT 
WHERE DEPARTMENT_NO IS NULL;

-- 8. 
SELECT CLASS_NO 
FROM TB_CLASS 
WHERE PREATTENDING_CLASS_NO IS NOT NULL;

-- 9.
SELECT DISTINCT CATEGORY
FROM TB_DEPARTMENT;
SELECT UNIQUE CATEGORY
FROM TB_DEPARTMENT;

-- 10.
SELECT STUDENT_NO , STUDENT_NAME , STUDENT_SSN , ENTRANCE_DATE 
FROM TB_STUDENT 
WHERE ABSENCE_YN = 'N' 
	AND STUDENT_ADDRESS LIKE '전주%'
	AND ENTRANCE_DATE LIKE '02%'
	AND EXTRACT( YEAR FROM ENTRA);


